### ISSUE TITLE
No lbfgsb_wrapper in java.library.path exception when trying to run SampleRun class

### ISSUE THREAD

**Issue by nkataieva** [mkobos/lbfgsb_wrapper#6]
Hello,

We are trying to use lbfgsb-1.1.5.jar within maven project. It being downloaded via maven from private repository to local repository. Project is running on Debian. When running SampleRun class from our application we get:
`java.lang.UnsatisfiedLinkError: no lbfgsb_wrapper in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at lbfgsb.Wrapper.<clinit>(Wrapper.java:15)
        at lbfgsb.Minimizer.run(Minimizer.java:99)
        at lbfgsb.SampleRun.main(SampleRun.java:14)`

I tried to set java.library.path in a different ways:
1. System.setProperty("java.library.path", "..."), trying both pointing to local maven repository where jar is located and putting jar within project folder.
2. Also added -Djava.library.path="/path/to/folder/where/jar/located/"
3. System.load("/path/to/jar/")
None of this haven't worked for us. Some maybe you know how to resolve it?

Thank you.

**Comment by mkobos** [comment]
Hi. This looks like an error that is printed when the shared binary library build from the source (it's name is `liblbfgsb_wrapper.so` in Linux) is not in `java.library.path`. Have you tried to run the jar file through `bin/linux_run1.sh` or `bin/linux_run2.sh` scripts from the root directory of the project?

**Comment by nkataieva** [comment]
Yes, I managed to run jar file running linux_run1.sh and linux_run2.sh scripts from the root of the project lbfgsb_wrapper. But when trying running it from project in which I try to use jar - it gives me error that I described in this issue.

**Comment by nkataieva** [comment]
Also I found liblbfgsb_wrapper.so in built project folder. If I understood correctly I need to point on it from project in which I am trying to use lbfgsb_wrapper.jar.

**Comment by mkobos** [comment]
Yes. I don't know what is your exact configuration, but as long as `liblbfgsb_wrapper.so` is in the `java.library.path` used by your application (that in turn uses the `lbfgsb_wrapper-*.jar`), this error should not occur.
